name: Playwright Tests
on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04 # Specify a stable Ubuntu version to avoid compatibility issues
    environment: production
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install missing dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libasound2 \
          libicu70 || sudo apt-get install -y libicu-dev \
          libffi7 || sudo apt-get install -y libffi-dev \
          libx264-163 || sudo apt-get install -y libx264
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
